Storybook router
ZakkMan/modern-trousseau pull request #47
Opened 2020-01-07 17:29 UTC by jmripper

added in the storybook router

2020-01-07 18:45 UTC, mrrogercampbell reviewed
Over all this looks really good. Drop in a view comments below, please review. Let me know if you have any questions.

2020-01-07 18:45 UTC, rc1336 commented on client/src/components/NavMenu/NavMenu.css
> +.nav-container nav {
Could you use a specific class name here?

2020-01-07 18:45 UTC, rc1336 commented on client/src/components/NavMenu/NavMenu.css
> +.nav-container nav ul {
Could you use a specific class name here?

2020-01-07 18:45 UTC, rc1336 commented on client/src/components/NavMenu/NavMenu.js
> +                            <h3 className="nav-title">Home</h3>
Please fix your indentations here. Might be helpful for you to install a React linter.

2020-01-07 18:57 UTC, mrrogercampbell reviewed
Also when I try to run your branch it is throwing errors. Does this code compile for you?

2020-01-07 18:57 UTC, rc1336 commented on client/src/components/NavMenu/NavMenu.js
> +import React, { Component } from 'react';
You do not need to import `Component` if you are not going to use it.

2020-01-07 18:59 UTC, rc1336 commented
Also please add a link to the issue for this feature. If there is not one create please make on. Thanks!

2020-01-07 19:39 UTC, 0xZakk requested changes
@jmripper There's a lot of stuff in here from your work on the nav menu. Can you fix this so it's just the storybook react-router stuff?

2020-01-07 19:51 UTC, jmripper commented
@ZakkMan does that mean to delete all the nav menu stuff I have? I just want to make sure that's what you're saying.

2020-01-08 14:17 UTC, ZakkMan commented
@jmripper Know we spoke about this in person, but so we have it all here too: you don't want to delete the files, you just want to remove them from this PR

2020-01-08 15:45 UTC, 0xZakk approved these changes

2020-01-08 15:45 UTC, ZakkMan commented
@jmripper Fantastic job!

2020-01-08 15:45 UTC, merged