Adam DeLessio - Card component
ZakkMan/modern-trousseau pull request #48
Opened 2020-01-07 18:37 UTC by Adam-DeLessio

I could not figure out how to use the font I imported. Other than that everything is complete.

2020-01-07 18:58 UTC, rc1336 commented
Can you please give me more context on what it is you did? Also please provide a link to the issue you worked on in your comment. Thanks.

2020-01-07 19:50 UTC, 0xZakk reviewed
@Adam-DeLessio A lot of really great progress here! Super impressive! Some feedback for you below

2020-01-07 19:50 UTC, ZakkMan commented on client/public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
Jenny created a branch that added this stuff and it's been merged in to `develop`. All you need to do is pull `develop` and merge it into your branch.

2020-01-07 19:50 UTC, ZakkMan commented on client/src/components/Card/Card.css
> +	width: 234px;
We may not want and absolute height and width for this - the sizing may need to be determined by the contents or the context

2020-01-07 19:50 UTC, ZakkMan commented on client/src/components/Card/Card.css
> +	box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
This is a great touch 👌

2020-01-07 19:50 UTC, ZakkMan commented on client/src/components/Card/Card.css
> +.cardTitle {
Can you make all your CSS class names all lower case and separated by dashes? I.e. `.card-title`, rather than `.cardTitle`?

2020-01-07 19:50 UTC, ZakkMan commented on client/src/components/Card/Card.js
> +	]
This is all information that should be passed in as props - probably to create 3 instances of this `Card` component

2020-01-07 19:50 UTC, ZakkMan commented on client/src/components/Card/Card.js
> +	let newMap = cards.map(card =>  {
Be sure to use semantic names for things. Your team will have no way of knowing what `newMap` is for or what it holds based just on the name

2020-01-07 19:50 UTC, ZakkMan commented on client/src/components/Card/Card.stories.js
> +	.add('Card', () => (<Card label='' type='card' />))
Do you need a `label` prop`? Or a `type` prop?

2020-01-07 19:50 UTC, ZakkMan commented on client/src/components/CardIcon.js
> +export default Icon;
Can you delete all this? If you need an icon, then you're going to use the `Icon` component that Kelly is working on!

2020-01-07 21:25 UTC, Adam-DeLessio commented
Link: https://github.com/ZakkMan/modern-trousseau/issues/1

I've made the corrections you asked the way I interpreted them. I think I merged the develop branch like you said to, but I'm not sure if I did it correctly.

2020-01-08 15:46 UTC, 0xZakk requested changes
@Adam-DeLessio My bad! I created a review and then forgot to send it back to you! Here's my feedback. This is a really great start!

2020-01-08 15:46 UTC, 0xZakk commented on client/public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
@Adam-DeLessio looks like you missed this one?

2020-01-08 15:46 UTC, 0xZakk commented on client/src/components/Card/Card.js
> +	]
This is data we want to pass into the Card component as props - this is data from the mock, but that is just sample data.

Ideally, we could render a card component like this:

```jsx
<Card>
  <Icon type="calendar" />
  <h3>Book With Us</h3>
  <p>Spend an hour with us to create a truly unique, personalized & flattering wedding dress.</p>
</Card>
```

2020-01-08 15:46 UTC, 0xZakk commented on client/src/components/Card/Card.js
> +	]
(This is where `props.children` come into play)

2020-01-08 15:46 UTC, 0xZakk commented on client/src/components/Card/SingleCard.css
> +}
This stuff is going to be determined by what is rendered into the component

2020-01-08 15:46 UTC, 0xZakk commented on client/src/components/Card/SingleCard.css
> +}
So I don't think you need styles for these

2020-01-08 15:46 UTC, 0xZakk commented on client/src/components/CardIcon.js
> +export default Icon;
@Adam-DeLessio looks like you missed this one too

2020-01-08 15:46 UTC, 0xZakk commented on client/src/components/Card/SingleCard.js
> +export default SingleCard
Do you need this? We already have the `Card` component you're building out

2020-01-08 19:47 UTC, 0xZakk requested changes
Couple more things for you

2020-01-08 19:47 UTC, ZakkMan commented on client/src/components/Card/Card.js
> +			<p className='card-p'>{props.paraText}</p>
Can you come up with a semantic name for this? Something other than `card-p` or `paraText`?

2020-01-08 19:47 UTC, ZakkMan commented on client/src/components/Card/Card.stories.js
> +	.add('DressCard', () => (<Card type='card' icon='' title='' paraText='' />))
Do you need to populate these strings? Also, do you need the `type` prop?

2020-01-08 20:18 UTC, 0xZakk requested changes
@Adam-DeLessio Code looks good, just need to polish up the styling a bit. This is what I see:

![Screen Shot 2020-01-08 at 3 17 59 PM](https://user-images.githubusercontent.com/4991553/72012519-2771b500-322a-11ea-85d6-bbe1511d7353.png)

2020-01-08 20:47 UTC, Adam-DeLessio commented
I'm not sure what to do about the icon part. I'm a little confused because I had styled the cards earlier and I thought you said to remove it. I could be mistaken though.

2020-01-08 20:49 UTC, 0xZakk requested changes
@Adam-DeLessio Sorry for the confusion. There's now an `Icon` component that you should use in this `Card` component. And we want the styling here to match what's in the mock as closely as possible.

2020-01-09 15:10 UTC, Adam-DeLessio commented
There is no 'dress' icon available in the Icon component so I just picked a different one as a place holder.

2020-01-09 16:46 UTC, 0xZakk requested changes
@Adam-DeLessio This looks so good!! Really great work! Just one small thing to make it better

2020-01-09 16:46 UTC, ZakkMan commented on client/src/components/Card/Card.js
> +			<Icons name={useIcon} size='3x' />
You can just pass down the prop here

2020-01-09 16:46 UTC, ZakkMan commented on client/src/components/Card/Card.js
> +	}
This is clever! You can simplify this a lot by just passing dow the icon as a prop

2020-01-09 16:54 UTC, mrrogercampbell requested changes
Your code base is throw quite a few errors. I know some are due to the `date-picker` component, which is currently being worked on. But you also are throwing other errors please remedy those and update this PR when done. Thanks.

2020-01-09 16:54 UTC, rc1336 commented on client/public/index.html
> +
Please remove this spacing it is not needed.

2020-01-09 16:54 UTC, rc1336 commented on client/src/components/Card/Card.js
> +	return(
You do not need an empty line here. Please remove it.

2020-01-09 16:54 UTC, rc1336 commented on client/src/components/DatePicker/DatePicker.stories.js
> +    .add('DatePicker', () => <DatePicker label={"Requested Date*"} name={"Requested Date"} value={"November 11"} min={"February 29, 2020"} step={"1"} max={"February 28, 2022"} onChange={handleChange}
This code is causing issues in your code base. For now comment it out until the person who is working on it fixes the bugs it introduces.

2020-01-09 17:00 UTC, Adam-DeLessio commented
I commented out the date-picker-stories file.

2020-01-09 17:09 UTC, mrrogercampbell approved these changes
Code looks great! Awesome job! @ZakkMan I believe this is ready to be merged into develop.

2020-01-09 18:46 UTC, 0xZakk requested changes
@Adam-DeLessio It looks like there's a conflict with develop. Can you fix that? Once that's fixed, this will be ready to merge

2020-01-09 18:54 UTC, Adam-DeLessio commented
Should be good now.

2020-01-09 19:11 UTC, 0xZakk approved these changes
@Adam-DeLessio Looks great! Really great work!

2020-01-09 19:11 UTC, merged