Button component
ZakkMan/modern-trousseau pull request #56
Opened 2020-01-08 14:33 UTC by jcasado6

changed around class names and reorganized css per your messages yesterday.

2020-01-08 15:47 UTC, ZakkMan commented
@jcasado6 Is this a new PR? It looks like there aren't any changes requested here

2020-01-08 15:54 UTC, 0xZakk requested changes
See my comment

2020-01-08 16:18 UTC, jcasado6 commented
Yes, this is a new PR with changes because the original one was closed due to the accidental merge.

2020-01-08 19:52 UTC, mrrogercampbell requested changes
Hey @jcasado6 it doesnt look like any of your css is being utilized. All I see is a white button.

2020-01-08 20:28 UTC, mrrogercampbell requested changes
Hey @ZakkMan I just re-reviewed @jcasado6 code and it looks good. 

Only thing is with him recreating this PR none of his commit history is showing. Not sure why. 

I feel like this is ready to be merged in to develop.

2020-01-09 19:36 UTC, mrrogercampbell approved these changes
@ZakkMan I believe this component is complete.

2020-01-09 19:41 UTC, 0xZakk requested changes
@jcasado6 Overall this looks really good. The font looks a little off though. Can you verify that this is the correct font?

2020-01-09 19:59 UTC, jcasado6 commented
updated large button font family

2020-01-10 14:29 UTC, 0xZakk requested changes
@jcasado6 Just a few small things

2020-01-10 14:29 UTC, ZakkMan commented on client/src/components/Button/Button.css
> +  width: 88px;
Can you set padding here rather than a hard height and width?

2020-01-10 14:29 UTC, ZakkMan commented on client/src/components/Button/Button.css
> +  width: 88px;
This is for all of the buttons where you have an absolute value for width and height

2020-01-10 14:29 UTC, ZakkMan commented on client/src/components/Button/Button.stories.js
> +  .add("light-pink", () => <Button label="Book Now" type="light-pink" />)
Can you make these labels more human-friendly? Like `Light Pink`, `Dark Pink`, `Red`, etc

2020-01-10 15:53 UTC, jcasado6 commented
changed height&width to padding, changed story labels.

2020-01-10 19:27 UTC, 0xZakk approved these changes

2020-01-10 19:27 UTC, merged